# Generated by Django 3.2.3 on 2021-05-15 01:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('dni', models.PositiveIntegerField(verbose_name='DNI')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('date_of_admission', models.DateField(verbose_name='Date of admission')),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=200, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2, verbose_name='Gender')),
                ('marital_status', models.CharField(default='S', max_length=2, verbose_name='Marital Status')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+5491123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('certified', models.BooleanField(default=False)),
            ],
        ),
    ]
