# Generated by Django 3.2.3 on 2021-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='The name of the subject', max_length=255, verbose_name='Subject name'),
        ),
    ]
