# Generated by Django 3.2.3 on 2021-06-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ManyToManyField(to='classroom.SubjectGroup'),
        ),
    ]
